# SPDX-FileCopyrightText: 2024 Christina Sørensen
# SPDX-License-Identifier: EUPL-1.2
repos:
  - repo: local
    hooks:
      - id: rust-linting
        name: Rust linting
        description: Run rustfmt on included files
        entry: cargo fmt --
        types: [file, rust]
        language: system
      - id: rust-clippy
        name: Rust clippy
        description: Run clippy on included files
        pass_filenames: false
        entry: cargo clippy --workspace --all-targets --all-features
        types: [file, rust]
        language: system
