# SPDX-FileCopyrightText: 2024 Christina Sørensen
# SPDX-License-Identifier: EUPL-1.2
[toolchain]
# NOTE: don't forget to also update Cargo.toml and .github/workflows/unit-tests.yml
# At the time of writing, 1.90 is the latest version supported by OpenBSD
channel = "1.90"
profile = "default"
