FROM ubuntu:24.04

# Install dependencies
RUN apt-get update && \
    apt-get -y install curl sudo gcc \
    # We need these tools for specific tests
    attr git locales tzdata

COPY --from=ghcr.io/casey/just:latest /just /usr/local/bin/

# Generate locales
RUN sed -i '/fr_FR.UTF-8/s/^# //g' /etc/locale.gen && \
    sed -i '/ja_JP.UTF-8/s/^# //g' /etc/locale.gen && \
    locale-gen

# Configure test user
RUN groupadd -g 5677 eza_test && \
    groupadd -g 5678 eza_group && \
    groupadd -g 5679 eza_group2 && \
    useradd -G sudo,eza_test,eza_group2 -g eza_group -m -u 1234 eza_test && \
    sed -i 's/^%sudo.*$/%sudo ALL=(ALL:ALL) NOPASSWD: ALL/' /etc/sudoers

# Create working directories and volumes moint points
RUN mkdir -p /workspace/target && \
    mkdir -p /workspace/tests/data && \
    mkdir -p /home/eza_test/.cargo/registry && \
    chown -R eza_test: /workspace && \
    chown -R eza_test: /home/eza_test

USER eza_test

# Install Rust
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

# Configure git
RUN git config --global user.email "eza@eza.test" && \
    git config --global user.name "eza"

ENV PATH=/home/eza_test/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

WORKDIR /workspace
