FROM ubuntu:latest

# Install dependencies
RUN apt-get update && \
    apt-get -y install curl git sudo gcc locales

COPY --from=ghcr.io/casey/just:latest /just /usr/local/bin/

# Generate locales
RUN sed -i '/fr_FR.UTF-8/s/^# //g' /etc/locale.gen && \
    sed -i '/ja_JP.UTF-8/s/^# //g' /etc/locale.gen && \
    locale-gen

# Create working directories
RUN mkdir -p /workspace/target && \
    mkdir -p /workspace/tests/data && \
    chown -R ubuntu: /workspace

USER ubuntu

# Install Rust
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

ENV PATH=/home/ubuntu/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

WORKDIR /workspace
