FROM ubuntu:latest

# Install dependencies
RUN apt-get update && \
    apt-get -y install curl sudo gcc \
    # We need these tools for specific tests
    attr git locales tzdata

COPY --from=ghcr.io/casey/just:latest /just /usr/local/bin/

# Generate locales
RUN sed -i '/fr_FR.UTF-8/s/^# //g' /etc/locale.gen && \
    sed -i '/ja_JP.UTF-8/s/^# //g' /etc/locale.gen && \
    locale-gen

# Create working directories and volumes moint points
RUN mkdir -p /workspace/target && \
    mkdir -p /workspace/tests/data && \
    mkdir -p /home/ubuntu/.cargo/registry && \
    chown -R ubuntu: /workspace && \
    chown -R ubuntu: /home/ubuntu

USER ubuntu

# Install Rust
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y && \
    curl --proto '=https' --tlsv1.2 -fsSL https://github.com/taiki-e/cargo-hack/releases/latest/download/cargo-hack-x86_64-unknown-linux-gnu.tar.gz | tar xzf - -C /home/ubuntu/.cargo/bin

ENV PATH=/home/ubuntu/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

WORKDIR /workspace
