name: eza
version: 'latest'
summary: Replacement for 'ls' written in Rust
description: |
  It uses colours for information by default, helping you distinguish between
  many types of files, such as whether you are the owner, or in the owning
  group. It also has extra features not present in the original ls, such as
  viewing the Git status for a directory, or recursing into directories with a
  tree view. eza is written in Rust, and it’s small, fast, and portable.

grade: stable
confinement: classic

apps:
  eza:
    command: eza

parts:
  eza:
    plugin: rust
    source: .
    stage-packages:
      - libgit2-24
      - cmake
      - libz-dev
