# SPDX-FileCopyrightText: 2024 Christina Sørensen
# SPDX-License-Identifier: EUPL-1.2
name: eza
base: core24
version: 'latest'
summary: Replacement for 'ls' written in Rust
description: |
  It uses colours for information by default, helping you distinguish between
  many types of files, such as whether you are the owner, or in the owning
  group. It also has extra features not present in the original ls, such as
  viewing the Git status for a directory, or recursing into directories with a
  tree view. eza is written in Rust, and it's small, fast, and portable.
issues: https://github.com/eza-community/eza/issues
source-code: https://github.com/eza-community/eza
contact: christina@cafkafk.com
website: https://eza.rocks/
license: MIT
grade: stable
confinement: classic
apps:
  eza:
    command: bin/eza
parts:
  eza:
    plugin: rust
    source: .
    build-attributes:
      - enable-patchelf
    stage-packages:
      - cmake
      - libz-dev
platforms:
  amd64:
    build-on: [amd64, arm64]
  arm64:
    build-on: [amd64, arm64]
  armhf:
    build-on: [amd64, arm64]
